### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TitanNano** [lee-b/final-frontier#1]
I ported a large part of your code to Rust and would like to publish my changes on GitHub. Unfortunately, your code does not contain any LICENSE file. Would you mind adding one?

**Comment by lee-b** [comment]
Not my code, just some modifications on top of unmaintained code that was out there, but at risk of disappearing.

Now that you mention it I'm not 100% sure about the license.  I'm pretty sure it was public domain or something, or I wouldn't have forked it, but there's no license file included, and it's been a while.  If you have a more modern Rust-based port though, it might be good to drop this old repo (I don't use/maintain it anymore), and let people use the Rust version instead (I'm a Rust fan too).

Tom Morton is the original author of GLFrontier, and also works on Pioneer, if you want to get in touch: https://en.wikipedia.org/wiki/Pioneer_(video_game)

**Comment by echo2go** [comment]
Have a look at https://github.com/pcercuei/glfrontier 
It seems to be the original author and it is under GPL

**Comment by TitanNano** [comment]
@echo2go at the bottom of the readme it says t-morton@blueyonder.co.uk which indicates to me that Tom Morton is in fact the author. The comment about the GPL license seems to be a long the lines of "I have no idea which license to choose, so I choose the one that came to mind first". It certainty doesn't seem like he is very passionate about the license. That's why I'm asking for permission to put my modified code under the Apache- 2.0 license.

**Comment by lee-b** [comment]
Thanks for finding that, @echo2go.  So yes, it seems to be clearly GPL'd, which would mean, no, not Apache, @TitanNano , unless your code is sufficiently modified to constitute an original work.

**Comment by TitanNano** [comment]
It's up. https://github.com/TitanNano/final-frontier/tree/9bb6a762e7c14ef1d72f1d1db160688016cfbc66
